kind: List
apiVersion: v1
items:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: ci
  displayName: OpenShift CI
  description: Contains Jenkins server
- kind: Group
  apiVersion: v1
  metadata:
    name: ci-admins
  users:
  - smarterclayton
  - danmcp
  - liggitt
  - stevekuznetsov
  - jwforres
  - ncdc
- kind: ClusterRoleBinding
  apiVersion: v1
  metadata:
    name: ci-admins-to-cluster-admins
  subjects:
  - kind: Group
    name: ci-admins
  roleRef:
    name: cluster-admin
- kind: RoleBinding
  apiVersion: v1
  metadata:
    name: authenticated-users-to-view
    namespace: ci
  subjects:
  - kind: SystemGroup
    name: system:authenticated
  roleRef:
    name: view
