kind: Pod
apiVersion: v1
metadata:
  name: origin-gce-install
spec:
  containers:
  - name: pod
    image: openshift/gce-cloud-installer:latest
    resources:
      requests:
        cpu: 100m
        mem: 300M
    volumeMounts:
    - name: secrets
      mountPath: /usr/local/install/data
  volumes:
  - name: secrets
    secret:
      secretName: origin-gce

